version: "3.7"

services:
  stop-analyzing-api:
    image: local/stop-analyzing-api:0.0.1
    build: .
    ports:
      - 8000:8000
    restart: always
    environment:
      - STPA_API_LOG_LEVEL=info
      - STPA_API_PORT=8000

  postgres:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user2020
      - POSTGRES_PASSWORD=pass2020
      - POSTGRES_DB=stop-analyzing-api

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8008:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
